//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.28 at 10:48:30 AM SAMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://springCinema.com/cinema-web-service")
package com.springcinema.cinema_web_service;
