CREATE TABLE CINEMA_EVENT
(
  "ID" NUMBER(19,0) NOT NULL,
  "NAME" VARCHAR2(255) NOT NULL,
  BASE_PRICE NUMBER(31,10) NOT NULL,
  RATIN_SYS_NAME VARCHAR2(255) NOT NULL,
  CONSTRAINT "PK_CINEMA_EVENT" PRIMARY KEY ("ID")
);
CREATE SEQUENCE CINEMA_EVENT_SEQ MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1;

CREATE TABLE CINEMA_AIR_DATES
(
  EVENT_ID NUMBER(19,0) NOT NULL,
  "DATE" TIMESTAMP NOT NULL
);

CREATE TABLE CINEMA_EVENT_AUDITORIUM_LINK
(
  EVENT_ID NUMBER(19,0) NOT NULL,
  "DATE" TIMESTAMP NOT NULL,
  AUDITORIUM_ID NUMBER(19,0) NOT NULL
);

CREATE TABLE CINEMA_AUDITORIUM
(
  "ID" NUMBER(19,0) NOT NULL,
  "NAME" VARCHAR2(255) NOT NULL,
  NUMBER_OF_SEATS NUMBER(19,0) NOT NULL,
  VIP_SEATS VARCHAR2(512),
  CONSTRAINT "PK_CINEMA_AUDITORIUM" PRIMARY KEY ("ID")
);
CREATE SEQUENCE CINEMA_AUDITORIUM_SEQ MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1;

CREATE TABLE CINEMA_TICKET
(
  "ID" NUMBER(19,0) NOT NULL,
  USER_LOGIN VARCHAR2(255) NOT NULL,
  EVENT_ID NUMBER(19,0) NOT NULL,
  "DATE" TIMESTAMP NOT NULL,
  SEAT NUMBER(19,0) NOT NULL,
  PRICE NUMBER(31,10) NOT NULL,
  IS_LUCKY NUMBER(1,0),
  CONSTRAINT "PK_CINEMA_TICKET" PRIMARY KEY ("ID")
);
CREATE SEQUENCE CINEMA_TICKET_SEQ MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1;

CREATE TABLE CINEMA_USER
(
  LOGIN VARCHAR2(255) NOT NULL,
  FIRST_NAME VARCHAR2(255),
  LAST_NAME VARCHAR2(255),
  EMAIL VARCHAR2(255),
  ROLE_SYS_NAME VARCHAR2(255) NOT NULL,
  BIRTHDAY DATE,
  CONSTRAINT "PK_CINEMA_USER" PRIMARY KEY (LOGIN)
);

CREATE TABLE ASPECTS_COUNTERS
(
    ASPECT_NAME VARCHAR2(255) NOT NULL,
    ASPECT_COUNTER NUMBER(19,0) NOT NULL
);

commit;

INSERT INTO CINEMA_USER(LOGIN, ROLE_SYS_NAME) VALUES ('admin', 'ADMIN');